// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ChatroomSubscriptionController from "./chatroom_subscription_controller"
application.register("chatroom-subscription", ChatroomSubscriptionController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import NavbarController from "./navbar_controller"
application.register("navbar", NavbarController)

import NewMessageController from "./new_message_controller"
application.register("new-message", NewMessageController)

import PrivateChatroomSubscriptionController from "./private_chatroom_subscription_controller"
application.register("private-chatroom-subscription", PrivateChatroomSubscriptionController)

import ReadMessageController from "./read_message_controller"
application.register("read-message", ReadMessageController)
