// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CarouselController from "./carousel_controller"
application.register("carousel", CarouselController)

import ChatroomSubscriptionController from "./chatroom_subscription_controller"
application.register("chatroom-subscription", ChatroomSubscriptionController)

import EditJobPostingController from "./edit_job_posting_controller"
application.register("edit-job-posting", EditJobPostingController)

import FavoriteController from "./favorite_controller"
application.register("favorite", FavoriteController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import InsertInListController from "./insert_in_list_controller"
application.register("insert-in-list", InsertInListController)

import NavbarController from "./navbar_controller"
application.register("navbar", NavbarController)

import NewMessageController from "./new_message_controller"
application.register("new-message", NewMessageController)

import NotificationsController from "./notifications_controller"
application.register("notifications", NotificationsController)

import PrivateChatroomSubscriptionController from "./private_chatroom_subscription_controller"
application.register("private-chatroom-subscription", PrivateChatroomSubscriptionController)

import ReadMessageController from "./read_message_controller"
application.register("read-message", ReadMessageController)


import ReplyController from "./reply_controller"
application.register("reply", ReplyController)

import FavoriteController from "./favorite_controller"
application.register("favorite", FavoriteController)

